// --- UI ACTION TYPES ---
export const TOGGLE_TIME_FORMAT = 'TOGGLE_TIME_FORMAT';

// --- DATA ACTION TYPES ---

// For timezones
export const FETCH_TIMEZONES = 'FETCH_TIMEZONES';

// For baseTimezone
export const GET_BASE_TIMEZONE = 'GET_BASE_TIMEZONE';
export const SET_BASE_TIMEZONE = 'SET_BASE_TIMEZONE';

// For trackedTimezones
export const GET_TRACKED_TIMEZONES = 'GET_TRACKED_TIMEZONES';
export const ADD_TRACKED_TIMEZONES = 'ADD_TRACKED_TIMEZONES';
export const REMOVE_TRACKED_TIMEZONES = 'REMOVE_TRACKED_TIMEZONES';
export const UPDATE_TRACKED_TIMEZONES = 'UPDATE_TRACKED_TIMEZONES';